name: Remote Year
favicon: null
layout_spectrum: 0.09016
typography_spectrum: 0.37396
title: '12 cities, 11 countries, 12 months'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#000000'
    - '#333333'
    - '#400000'
    - '#400040'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
