name: Remote Year
favicon: null
layout_spectrum: 0.96661
typography_spectrum: 0.37396
title: '12 cities, 11 countries, 12 months'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#81b3ca'
    - '#038cb4'
    - '#000000'
    - '#33301f'
    - '#ded9c2'
  brandStrength: 0.0625
  lightness: 0.6557646167930216
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
